-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgCp2COGmakyCdEdm4
KGQwUkBCYP7LwNsXlkwYqZ/AqJCgCgYIKoZIzj0DAQehRANCAATOfs3dcMu5XeLN
Xr+D6nXE6q0Nnji9zqnKPSxnzu/uF/TeMTGqYB2CR4pjMi9a7Ak0P66VSXsePbnd
lzvOIKf7
-----END PRIVATE KEY-----